name: Test
version: '${project.version}'
author: TerrorByte
description: Test plugin
main: me.terrorbyte.test.Test
load: POSTWORLD
depend: [Honeypot]

commands:
  testcommand: 
    description: Tests the event
  checkblock:
    description: Checks the block