name: Test
version: '@version@'
author: TerrorByte
description: Test plugin
main: me.terrorbyte.test.Test
load: STARTUP
depend: [Honeypot]

commands:
  testcommand: 
    description: Tests the event
  checkblock:
    description: Checks the block