name: Test
version: '1.0'
author: TerrorByte
description: Test plugin
main: me.terrorbyte.test.Test
api-version: 1.17
load: POSTWORLD
depend: [Honeypot]

commands:
  testcommand: 
    description: Tests the event